package com.fptcampus.lostfoundfptcampus.model.dto;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 * DTO for creating new LostItem
 * Only includes fields needed for POST request
 * NOTE: uuid is generated by server, but userId must be provided
 */
public class CreateItemRequest {
    @Expose
    @SerializedName("userId")
    private Long userId;

    @Expose
    @SerializedName("lostUserId")
    private Long lostUserId;

    @Expose
    @SerializedName("foundUserId")
    private Long foundUserId;

    @Expose
    @SerializedName("returnedUserId")
    private Long returnedUserId;

    @Expose
    @SerializedName("title")
    private String title;

    @Expose
    @SerializedName("description")
    private String description;

    @Expose
    @SerializedName("category")
    private String category;

    @Expose
    @SerializedName("status")
    private String status;

    @Expose
    @SerializedName("latitude")
    private Double latitude;

    @Expose
    @SerializedName("longitude")
    private Double longitude;

    @Expose
    @SerializedName("imageUrl")
    private String imageUrl;

    // Constructors
    public CreateItemRequest() {
    }

    public CreateItemRequest(String title, String description, String category, String status, 
                            Double latitude, Double longitude, String imageUrl) {
        this.title = title;
        this.description = description;
        this.category = category;
        this.status = status != null && !status.isEmpty() ? status : "lost";
        this.latitude = latitude;
        this.longitude = longitude;
        this.imageUrl = imageUrl;
    }

    // Getters and Setters
    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getLostUserId() {
        return lostUserId;
    }

    public void setLostUserId(Long lostUserId) {
        this.lostUserId = lostUserId;
    }

    public Long getFoundUserId() {
        return foundUserId;
    }

    public void setFoundUserId(Long foundUserId) {
        this.foundUserId = foundUserId;
    }

    public Long getReturnedUserId() {
        return returnedUserId;
    }

    public void setReturnedUserId(Long returnedUserId) {
        this.returnedUserId = returnedUserId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
}
